apiVersion: v2
name: nginx
description: Just a nginx Helm Chart for testing purposes

type: application
version: 0.1.3
appVersion: "1.24.0"

maintainers:
  - name: Alexander Neumann
    email: aleneum@gmail.com
